const ADMIN_USER="admin",ADMIN_PASS="admin123",KEY_FROTA="maquinapro_frota",KEY_HIST="maquinapro_historico",KEY_SESSION="maquinapro_admin";
const inicial=[{id:1,registro:"REG-001",categoria:"Escavadeira",quantidade:5,status:"Disponível",atualizado:"17/08/2026 22:00"},{id:2,registro:"REG-002",categoria:"Retroescavadeira",quantidade:3,status:"Em operação",atualizado:"17/08/2026 21:30"},{id:3,registro:"REG-003",categoria:"Pá carregadeira",quantidade:2,status:"Em manutenção",atualizado:"17/08/2026 20:15"},{id:4,registro:"REG-004",categoria:"Motoniveladora",quantidade:4,status:"Disponível",atualizado:"17/08/2026 19:45"}];
function getFrota(){let d=localStorage.getItem(KEY_FROTA);if(!d){localStorage.setItem(KEY_FROTA,JSON.stringify(inicial));return [...inicial]}return JSON.parse(d)}
function saveFrota(f){localStorage.setItem(KEY_FROTA,JSON.stringify(f))}
function hist(){return JSON.parse(localStorage.getItem(KEY_HIST)||"[]")}
function now(){return new Date().toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"})}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function cls(s){return s==="Disponível"?"available":s==="Em operação"?"busy":s==="Em manutenção"?"maint":s==="Reservado"?"reserved":"inactive"}
function addHist(m,acao){let h=hist();h.unshift({registro:m.registro,categoria:m.categoria,status:m.status,acao,data:now()});localStorage.setItem(KEY_HIST,JSON.stringify(h.slice(0,50)))}

const KEY_COMUNICADOS="maquinapro_comunicados";
function getComunicados(){return JSON.parse(localStorage.getItem(KEY_COMUNICADOS)||"[]")}
function saveComunicados(x){localStorage.setItem(KEY_COMUNICADOS,JSON.stringify(x))}
function renderComunicadosAdmin(){
 const el=document.getElementById("comunicadosAdmin"); if(!el)return;
 const d=getComunicados();
 el.innerHTML=d.map(x=>`<div class="comm-item"><div><strong>${esc(x.titulo)}</strong><small>${esc(x.tipo)} • ${esc(x.data)}</small><small>${esc(x.mensagem)}</small></div><div class="comm-actions"><button class="action" onclick="alternarComunicado('${x.id}')">${x.publicado?"Despublicar":"Publicar"}</button><button class="action danger" onclick="excluirComunicado('${x.id}')">Excluir</button></div></div>`).join("")||'<p>Nenhum comunicado cadastrado.</p>';
}
function alternarComunicado(id){let d=getComunicados(),x=d.find(a=>a.id===id);if(!x)return;x.publicado=!x.publicado;saveComunicados(d);renderComunicadosAdmin();toast(x.publicado?"Comunicado publicado.":"Comunicado despublicado.")}
function excluirComunicado(id){if(!confirm("Excluir este comunicado?"))return;saveComunicados(getComunicados().filter(x=>x.id!==id));renderComunicadosAdmin();toast("Comunicado excluído.")}

function renderFrota(){if(!document.getElementById("tabelaFrota"))return;let q=(document.getElementById("busca").value||"").toLowerCase(),f=getFrota().filter(m=>(m.registro+" "+m.categoria+" "+m.status).toLowerCase().includes(q));document.getElementById("tabelaFrota").innerHTML=f.map(m=>`<tr><td><strong>${esc(m.registro)}</strong></td><td>${esc(m.categoria)}</td><td>${m.quantidade}</td><td><span class="badge ${cls(m.status)}">${esc(m.status)}</span></td><td>${esc(m.atualizado)}</td><td><button class="action" onclick="editar(${m.id})">Editar</button><button class="action danger" onclick="excluirRegistro(${m.id})">Excluir</button></td></tr>`).join("")||'<tr><td colspan="6">Nenhum registro encontrado.</td></tr>';let all=getFrota();document.getElementById("totalRegistros").textContent=all.length;document.getElementById("totalMaquinas").textContent=all.reduce((a,x)=>a+Number(x.quantidade||0),0);document.getElementById("disponiveis").textContent=all.filter(x=>x.status==="Disponível").reduce((a,x)=>a+Number(x.quantidade||0),0);document.getElementById("manutencao").textContent=all.filter(x=>x.status==="Em manutenção").reduce((a,x)=>a+Number(x.quantidade||0),0);renderHistorico()}
function renderHistorico(){if(!document.getElementById("historico"))return;let h=hist();document.getElementById("historico").innerHTML=h.slice(0,8).map(x=>`<div class="allocation"><div><strong>${esc(x.registro)} — ${esc(x.categoria)}</strong><small>${esc(x.acao)}</small></div><div><strong>${esc(x.status)}</strong><small>${esc(x.data)}</small></div></div>`).join("")||'<p>Nenhuma alteração registrada.</p>'}
function abrirCadastro(){document.getElementById("modalTitulo").textContent="Novo registro";["fId","fRegistro","fCategoria","fQuantidade"].forEach(id=>document.getElementById(id).value="");document.getElementById("fStatus").value="Disponível";document.getElementById("modal").classList.add("show")}
function editar(id){let m=getFrota().find(x=>x.id===id);if(!m)return;document.getElementById("modalTitulo").textContent="Editar registro";document.getElementById("fId").value=m.id;document.getElementById("fRegistro").value=m.registro;document.getElementById("fCategoria").value=m.categoria;document.getElementById("fQuantidade").value=m.quantidade;document.getElementById("fStatus").value=m.status;document.getElementById("modal").classList.add("show")}
function fecharModal(){document.getElementById("modal").classList.remove("show")}
function excluirRegistro(id){let m=getFrota().find(x=>x.id===id);if(!m||!confirm("Excluir o registro "+m.registro+"?"))return;saveFrota(getFrota().filter(x=>x.id!==id));addHist(m,"Registro excluído");renderFrota();toast("Registro excluído.")}
function logout(){localStorage.removeItem(KEY_SESSION);location.href="login.html"}
function toast(t){let e=document.getElementById("toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2500)}
const login=document.getElementById("loginForm");if(login)login.addEventListener("submit",e=>{e.preventDefault();if(document.getElementById("loginUser").value.trim()===ADMIN_USER&&document.getElementById("loginPass").value===ADMIN_PASS){localStorage.setItem(KEY_SESSION,"admin");location.href="admin.html"}else document.getElementById("loginError").textContent="Usuário ou senha inválidos."});
if(location.pathname.endsWith("/admin.html")||location.pathname.endsWith("\\admin.html")){if(localStorage.getItem(KEY_SESSION)!=="admin")location.href="login.html";else{const cf=document.getElementById("comunicacaoForm"); if(cf) cf.addEventListener("submit",e=>{e.preventDefault(); const tipo=document.getElementById("cTipo").value,titulo=document.getElementById("cTitulo").value.trim(),mensagem=document.getElementById("cMensagem").value.trim(); if(!titulo||!mensagem)return; const d=getComunicados(); const dt=new Date(); d.unshift({id:String(Date.now()),tipo,titulo,mensagem,publicado:true,dataIso:dt.toISOString(),data:dt.toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"})}); saveComunicados(d.slice(0,100)); cf.reset(); renderComunicadosAdmin(); toast("Comunicado publicado com sucesso!");}); renderComunicadosAdmin(); renderFrota();window.addEventListener("storage",renderFrota);document.getElementById("frotaForm").addEventListener("submit",e=>{e.preventDefault();let f=getFrota(),id=document.getElementById("fId").value,registro=document.getElementById("fRegistro").value.trim(),categoria=document.getElementById("fCategoria").value.trim(),quantidade=Number(document.getElementById("fQuantidade").value),status=document.getElementById("fStatus").value;if(!registro||!categoria||quantidade<0)return;const registroNormalizado=registro.trim().toUpperCase(); const registroDuplicado=f.some(x=>String(x.registro).trim().toUpperCase()===registroNormalizado&&String(x.id)!==String(id)); if(registroDuplicado){toast("Este registro já está cadastrado. Escolha outro registro.");return}let data=now();if(id){let m=f.find(x=>String(x.id)===String(id)),antigo=m.status;Object.assign(m,{registro,categoria,quantidade,status,atualizado:data});addHist(m,antigo!==status?`Status alterado de "${antigo}" para "${status}"`:"Registro atualizado")}else{let m={id:Date.now(),registro,categoria,quantidade,status,atualizado:data};f.push(m);addHist(m,"Novo registro cadastrado")}saveFrota(f);renderFrota();fecharModal();toast("Registro salvo com sucesso!")});document.getElementById("modal").addEventListener("click",e=>{if(e.target.id==="modal")fecharModal()})}}
